simulations:
    myflat:
        topology: 'flat 10'
        simulations-number: 1
        regions: ['chr1_30']
        mutation-rates: [0.001, 0.005]
        chemistry: 'P6C4'
        coverages: [40, 60, 80]
        accuracies: [85, 90, 95]
        length-mean: 18000
        length-sd: 3000
        type: 'leaves'
    myrandom:
        topology: 'random 10'
        simulations-number: 4
        regions: ['chr1_30']
        mutation-rates: [0.001, 0.005]
        chemistry: 'P6C4'
        coverages: [40, 60, 80]
        accuracies: [85, 90, 95]
        length-mean: 18000
        length-sd: 3000
        type: 'all'
regions:
    chr1_30:
       coordinates: 'chr1:30000000-30200000'
       reference: 'hg38'
