simulations:
    myflat:
        topology: 'flat 10'
        simulations-number: 1
        regions: [ region1, region2 ]
        mutation-rates: [0.001, 0.005]
        chemistries: ['P6C4', 'R103']
        coverages: [40, 60, 80]
        accuracies: [85, 90, 95]
        length-mean: 18000
        length-sd: 3000
        type: 'leaves'
    myrandom:
        topology: 'random 10'
        simulations-number: 4
        regions: [ region2 ]
        mutation-rates: [0.001, 0.005]
        chemistries: ['P6C4', 'R103']
        coverages: [40, 60, 80]
        accuracies: [85, 90, 95]
        length-mean: 18000
        length-sd: 3000
        type: 'all'
regions:
    region1:
       chrom: 'chr1'
       start: 30000000
       end: 30500000
       reference: 'hg38'
    region2:
       chrom: 'chr2'
       start: 60000000
       end: 60500000
       reference: 'hg38'    
